# Generated by Django 4.2.1 on 2023-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Administration', 'Адміністрація'), ('Practice', 'Практика'), ('Introduction', 'Вступ')], max_length=128)),
            ],
        ),
    ]
