# Generated by Django 4.2.1 on 2023-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='fds', max_length=128),
            preserve_default=False,
        ),
    ]
