# Generated by Django 4.2.1 on 2023-05-27 19:24

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64)),
                ('day', models.CharField(choices=[('monday', 'Понеділок'), ('tuesday', 'Вівторок'), ('wednesday', 'Середа'), ('thursday', 'Четвер'), ('friday', "П'ятниця")], max_length=32)),
                ('subjects', django_jsonform.models.fields.JSONField()),
            ],
            options={
                'unique_together': {('group', 'day')},
            },
        ),
    ]
