# Generated by Django 4.2.1 on 2023-05-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_day_alter_schedule_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.CharField(max_length=64),
        ),
    ]
