# Generated by Django 4.2.1 on 2023-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
