# Generated by Django 4.2.1 on 2023-06-05 15:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='preview',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1280, None], upload_to='announcement/'),
        ),
    ]
