# Generated by Django 4.2.1 on 2023-05-22 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.PositiveIntegerField(verbose_name='ID користувача в телеграмі')),
                ('username', models.CharField(max_length=128, verbose_name="Ім'я користувача")),
                ('specialty', models.CharField(blank=True, max_length=128, null=True, verbose_name='Спеціальність студента')),
                ('course_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс студента')),
                ('group', models.CharField(blank=True, max_length=16, null=True, verbose_name='Група студента')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата створення профілю')),
            ],
            options={
                'verbose_name': 'Профіль',
            },
        ),
    ]
