# Generated by Django 4.2.1 on 2023-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID користувача в телеграмі'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=128, verbose_name='Нік користувача'),
        ),
    ]
