# Generated by Django 4.2.1 on 2023-05-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_group'),
        ('users', '0004_group_alter_userprofile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(max_length=32, verbose_name='Група студента'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
