# Generated by Django 4.2.1 on 2023-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_group_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Група студента'),
        ),
    ]
