# Generated by Django 4.2.1 on 2023-05-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_group_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course_num',
        ),
        migrations.AddField(
            model_name='group',
            name='course_num',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
