# Generated by Django 4.2.1 on 2023-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_course_num_group_course_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_id',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='ID чату в телеграмі'),
            preserve_default=False,
        ),
    ]
